name: ci-app-check

on: push

jobs:
  ci-app-check:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      # Ставим зависимости & build
      - run: make setup
      #start
      - run: make start
      # Запускаем линтер
      - run: make lint
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: run tests
        run: make test # name и run относятся к одной задаче, поэтому дефис ставится только перед name




